Repository nv-morpheus/MRC, pull requests merged in 2022-10, with the labels that each got.

#179 Fix returning of thread_binding attr
  src/public/options/fiber_pool.cpp
Labels: bug, non-breaking, review: ready

#180 Emit the value before incrementing the iterator fixes
  python/srf/_pysrf/src/segment.cpp
Labels: bug, non-breaking, review: ready

#182 Switch to github actions
  .github/workflows/pull_request.yml
  ci/Jenkinsfile
  ci/scripts/github/benchmark.sh
  ci/scripts/github/build.sh
  ci/scripts/github/checks.sh
  ci/scripts/github/common.sh
  ci/scripts/github/conda.sh
  ci/scripts/github/docs.sh
  ci/scripts/github/post_benchmark.sh
  ci/scripts/github/pre_benchmark.sh
  ci/scripts/github/test.sh
Labels: improvement, non-breaking, review: ready

#183 Add documentation on how to build the doxygen docs
  CONTRIBUTING.md
Labels: doc, non-breaking, review: ready

#188 Fetch history and tags for package step
  .github/workflows/pull_request.yml
Labels: bug, non-breaking, review: ready

#177 update abseil, grpc, and ucx versions for cuml compatibility
  Dockerfile
  ci/conda/environments/ci_env.yml
  ci/conda/environments/dev_env.yml
  ci/conda/environments/dev_env_nogcc.yml
  ci/conda/recipes/libsrf/build.sh
  ci/conda/recipes/libsrf/conda_build_config.yaml
  ci/conda/recipes/libsrf/meta.yaml
  cmake/dependencies.cmake
  cmake/deps/Configure_gRPC.cmake
  cmake/deps/Configure_ucx.cmake
Labels: bug, breaking

#191 Updating SRF versions from 22.09 to 22.11
  CMakeLists.txt
  docs/quickstart/CMakeLists.txt
  docs/quickstart/environment_cpp.yml
Labels: bug, non-breaking

#193 Registered memory should be released before the UCX Context is destroyed
  src/tests/test_ucx.cpp
Labels: bug, non-breaking

#192 Fix tests so that the proper upstream build is used for the coverage test
  .github/workflows/pull_request.yml
  ci/scripts/github/test.sh
Labels: bug, non-breaking

#197 Add codecov upload
  .github/codecov.yml
  .github/workflows/pull_request.yml
  ci/scripts/github/build.sh
  ci/scripts/github/docs.sh
  ci/scripts/github/test.sh
Labels: improvement, non-breaking, review: ready

#201 change pull_request to pull_request_target
  .github/workflows/add_to_project.yml
Labels: bug, non-breaking, review: ready

#202 Fix help string for SRF_BUILD_DOCS
  CMakeLists.txt
Labels: bug, non-breaking, review: ready
