Repository nv-morpheus/MRC, pull requests merged in 2022-11, with the labels that each got.

#206 Improve NVML + MIG Behavior
  src/internal/system/device_info.cpp
  srf.code-workspace
Labels: improvement, non-breaking, review: ready

#208 Fix throwing errors from `Executor.join_async()`
  python/srf/_pysrf/src/executor.cpp
  python/srf/tests/CMakeLists.txt
  python/srf/tests/utils.cpp
  python/tests/test_executor.py
Labels: bug, non-breaking

#199 Add dockerfile for CI runners
  .github/workflows/ci_pipe.yml
  .github/workflows/pull_request.yml
  ci/conda/environments/ci_env.yml
  ci/runner/Dockerfile
  ci/runner/README.md
  ci/runner/build_and_push.sh
  ci/scripts/github/benchmark.sh
  ci/scripts/github/build.sh
  ci/scripts/github/checks.sh
  ci/scripts/github/common.sh
  ci/scripts/github/conda.sh
  ci/scripts/github/docs.sh
  ci/scripts/github/post_benchmark.sh
  ci/scripts/github/pre_benchmark.sh
  ci/scripts/github/test.sh
Labels: improvement, non-breaking, review: ready

#200 [FEA]: Replacing SRF markdown templates with yml forms
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation-request.md
  .github/ISSUE_TEMPLATE/documentation_request_correction.yml
  .github/ISSUE_TEMPLATE/documentation_request_new.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/submit-question.md
  .github/ISSUE_TEMPLATE/submit_question.yml
Labels: non-breaking, feature request, review: ready

#213 A couple last minute formatting fixes and version tweaks
  python/srf/tests/sample_modules.cpp
  python/srf/tests/test_edges.cpp
  python/srf/tests/utils.cpp
Labels: improvement, non-breaking

#220 Ensure interpreter is properly initialized, minor test fixes
  python/srf/_pysrf/tests/test_pipeline.cpp
  python/srf/_pysrf/tests/test_pysrf.hpp
Labels: bug, non-breaking

#224 Adds missing functionality to allow dynamic modules to forward their configuration to nested children.
  include/srf/segment/builder.hpp
  python/srf/_pysrf/include/pysrf/segment.hpp
  python/srf/_pysrf/src/segment.cpp
  python/srf/core/segment.cpp
  python/tests/test_module_registry.py
  src/public/segment/builder.cpp
Labels: improvement, non-breaking, review: ready

#230 Upgrade to C++20
  .clang-tidy
  .github/workflows/pull_request.yml
  CMakeLists.txt
  Dockerfile
  ci/conda/environments/clang_env.yml
  ci/conda/environments/dev_env.yml
  ci/conda/recipes/libmrc/conda_build_config.yaml
  ci/iwyu/mappings.imp
  ci/runner/Dockerfile
  ci/scripts/github/common.sh
  docs/quickstart/environment_cpp.yml
  include/mrc/codable/type_traits.hpp
  include/mrc/core/spin_lock_mutex.hpp
  include/mrc/data/reusable_pool.hpp
  include/mrc/memory/buffer_view.hpp
  python/mrc/_pymrc/include/pymrc/utils.hpp
  python/mrc/_pymrc/src/utilities/serializers.cpp
  src/internal/network/resources.hpp
  src/internal/system/thread.cpp
Labels: breaking, feature request, review: ready

#234 Workspace Update to allow indentation in CMake argument blocks
  mrc.code-workspace
Labels: non-breaking, feature request

#235 Update codeowners to MRC
  .github/CODEOWNERS
  ci/scripts/github/common.sh
Labels: improvement, non-breaking
