Repository nv-morpheus/MRC, pull requests merged in 2022-07, with the labels that each got.

#117 Fix `flatten()` Operator With Infinite Sources
  python/srf/_pysrf/src/operators.cpp
Labels: bug, non-breaking

#110 Transient Pool
  CMakeLists.txt
  src/internal/memory/transient_pool.cpp
  src/internal/memory/transient_pool.hpp
  src/tests/test_memory.cpp
Labels: non-breaking, feature request, ready for review

#137 fix faulty assumption about remote key sizes
  src/tests/test_network.cpp
Labels: bug, non-breaking, ready for review

#133 Update CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: doc, non-breaking

#139 Fix contributing guide build
  ci/conda/environments/dev_env.yml
Labels: bug, non-breaking, ready for review

#111 Network Options
  CMakeLists.txt
  src/internal/data_plane/server.hpp
  src/internal/memory/device_resources.cpp
  src/internal/network/resources.cpp
  src/internal/network/resources.hpp
  src/internal/resources/manager.cpp
  src/internal/system/engine_factory_cpu_sets.cpp
  src/internal/system/host_partition_provider.cpp
  src/internal/ucx/registration_resource.hpp
  src/internal/ucx/resources.cpp
  src/internal/ucx/resources.hpp
  src/tests/test_memory.cpp
  src/tests/test_network.cpp
  src/tests/test_options.cpp
  src/tests/test_partitions.cpp
  src/tests/test_ucx.cpp
Labels: non-breaking, feature request, ready for review

#141 Adjust contrib instructions for pip install location
  CONTRIBUTING.md
  README.md
Labels: doc, non-breaking

#130 Resolves issue-32, re-add stats watchers to Rx and Python nodes
  ci/scripts/jenkins/test.sh
  cmake/deps/Configure_boost.cmake
  include/srf/segment/builder.hpp
  python/srf/_pysrf/include/pysrf/node.hpp
  python/srf/_pysrf/src/segment.cpp
  python/tests/test_benchmarking.py
  python/tests/test_stat_gather.py
  tests/benchmarking/test_utils.cpp
Labels: bug, non-breaking, ready for review

#147 Fix CPP checks for CI
  ci/conda/environments/clang_env.yml
  ci/conda/environments/dev_env.yml
  ci/scripts/common.sh
  ci/scripts/cpp_checks.sh
  ci/scripts/jenkins/checks.sh
Labels: improvement, non-breaking

#112 Data Plane - Initial P2P and RDMA Get
  CMakeLists.txt
  include/srf/codable/encoded_object.hpp
  protos/srf/protos/codable.proto
  src/internal/data_plane/WIP.md
  src/internal/data_plane/callbacks.cpp
  src/internal/data_plane/callbacks.hpp
  src/internal/data_plane/client.cpp
  src/internal/data_plane/client.hpp
  src/internal/data_plane/instance.cpp
  src/internal/data_plane/request.cpp
  src/internal/data_plane/request.hpp
  src/internal/data_plane/resources.cpp
  src/internal/data_plane/resources.hpp
  src/internal/data_plane/server.cpp
  src/internal/data_plane/server.hpp
  src/internal/data_plane/tags.hpp
  src/internal/memory/device_resources.cpp
  src/internal/memory/device_resources.hpp
  src/internal/network/resources.cpp
  src/internal/network/resources.hpp
  src/internal/resources/forward.hpp
  src/internal/resources/manager.cpp
  src/internal/resources/partition_resources_base.cpp
  src/internal/resources/partition_resources_base.hpp
  src/internal/system/partition_provider.hpp
  src/internal/ucx/memory_block.cpp
  src/internal/ucx/memory_block.hpp
  src/internal/ucx/registration_resource.hpp
  src/internal/ucx/resources.cpp
  src/internal/ucx/resources.hpp
  src/internal/ucx/worker.cpp
  src/internal/ucx/worker.hpp
  src/public/codable/encoded_object.cpp
  src/public/runnable/launcher.cpp
  src/tests/test_network.cpp
  tests/test_codable.cpp
Labels: non-breaking, feature request, review: ready
