Repository nv-morpheus/MRC, pull requests merged in 2022-06, with the labels that each got.

#14 Use VS Code Workspaces
  .gitignore
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  srf.code-workspace
Labels: enhancement, non-breaking

#16 prefix CONCAT_STR -> SRF_CONCAT_STR
  include/srf/utils/string_utils.hpp
  src/internal/system/system.cpp
  src/public/utils/type_utils.cpp
  tests/test_node.cpp
Labels: non-breaking

#21 Add Support for RAPIDS 21.10
  ci/conda/recipes/libsrf/build.sh
  ci/conda/recipes/libsrf/conda_build_config.yaml
  ci/conda/recipes/libsrf/meta.yaml
Labels: non-breaking, feature request

#25 Fix Pins for abseil-cpp, grpc-cpp, and glog
  .gitignore
  CMakeLists.txt
  ci/conda/environments/dev_env.yml
  ci/conda/environments/dev_env_nogcc.yml
  ci/conda/recipes/libsrf/build.sh
  ci/conda/recipes/libsrf/conda_build_config.yaml
  cmake/dependencies.cmake
Labels: non-breaking, feature request

#30 Explicitly Specify Version for `rapids_export`
  CMakeLists.txt
Labels: bug, non-breaking

#31 Add two missing headers that caused clang compile errors.
  include/srf/metrics/registry.hpp
  src/internal/utils/ranges.hpp
Labels: non-breaking, improvement

#29 Improve error handling on pipeline::Controller updates
  src/internal/pipeline/controller.cpp
  src/tests/test_pipeline.cpp
Labels: bug, non-breaking

#28 adding PortGraph; validate Pipeline definitions
  CMakeLists.txt
  src/internal/executor/executor.cpp
  src/internal/pipeline/port_graph.cpp
  src/internal/pipeline/port_graph.hpp
  src/tests/test_pipeline.cpp
Labels: bug, non-breaking

#41 adding pragma once to logging.h
  include/srf/core/logging.hpp
Labels: non-breaking, improvement

#24 Enable CI for SRF
  ci/Jenkinsfile
  ci/conda/environments/ci_env.yml
  ci/conda/environments/clang_env.yml
  ci/scripts/jenkins/build.sh
  ci/scripts/jenkins/checks.sh
  ci/scripts/jenkins/common.sh
  ci/scripts/jenkins/conda.sh
  ci/scripts/jenkins/docs.sh
  ci/scripts/jenkins/test.sh
  src/tests/test_main.cpp
Labels: non-breaking, improvement

#52 Improvements Needed for Quickstart
  .gitignore
  ci/conda/environments/dev_env.yml
  ci/scripts/copyright.py
  cmake/import_rapids_cmake.cmake
  cmake/python_module_tools.cmake
  include/srf/node/rx_sink.hpp
  include/srf/utils/string_utils.hpp
  python/CMakeLists.txt
  python/MANIFEST.in
  python/setup.py
  python/srf/__init__.py
  python/srf/benchmarking/CMakeLists.txt
  python/srf/benchmarking/tracer.cpp
  python/srf/core/CMakeLists.txt
  python/srf/core/segment.cpp
  python/srf/core/segment_definition.cpp
  python/srf/py.typed
  python/srf/tests/CMakeLists.txt
  srf.code-workspace
Labels: non-breaking, feature request

#40 pimpl IBuilder
  CMakeLists.txt
  include/srf/internal/segment/ibuilder.hpp
  include/srf/segment/builder.hpp
  src/internal/segment/builder.cpp
  src/internal/segment/builder.hpp
  src/internal/segment/ibuilder.cpp
  src/public/segment/builder.cpp
Labels: non-breaking, improvement, ready for review

#60 Add pybind11-stubgen to the conda build
  ci/conda/environments/dev_env.yml
  ci/conda/recipes/libsrf/meta.yaml
Labels: bug, non-breaking

#70 Fix SRF Conda Upload
  ci/conda/README.md
  ci/conda/build_and_upload.sh
  ci/conda/recipes/run_conda_build.sh
  cmake/import_rapids_cmake.cmake
Labels: bug, non-breaking

#71 Apply PR #70 to Correct Branch
  ci/conda/README.md
  ci/conda/build_and_upload.sh
  ci/conda/recipes/run_conda_build.sh
  cmake/import_rapids_cmake.cmake
Labels: bug, non-breaking

#73 Changing RAPIDS_VERSION to SRF_RAPIDS_VERSION
  CMakeLists.txt
  ci/conda/recipes/libsrf/build.sh
  cmake/dependencies.cmake
  cmake/deps/Configure_RMM.cmake
  cmake/deps/Configure_ucx.cmake
Labels: bug, non-breaking

#42 adding Resuable<T> and ReusablePool<T>
  benchmarks/bench_srf.cpp
  include/srf/data/reusable_pool.hpp
  src/tests/CMakeLists.txt
  src/tests/nodes/common_nodes.cpp
  src/tests/nodes/common_nodes.hpp
  src/tests/test_next.cpp
  src/tests/test_pipeline.cpp
  src/tests/test_reusable_pool.cpp
Labels: non-breaking, improvement, ready for review

#79 host_partition_id incorrectly set with multiple gpus present
  include/srf/options/placement.hpp
  src/internal/system/partitions.cpp
  src/tests/test_partitions.cpp
Labels: bug, non-breaking

#83 Fix for pipelines beginning before start is called
  src/internal/executor/executor.cpp
Labels: bug, non-breaking, ready for review

#87 Moving the python_module_tools before the SRF import
  docs/quickstart/CMakeLists.txt
Labels: bug, non-breaking

#93 SRF README Update - In Preparation of Public Release
  README.md
  docs/imgs/srf_pipeline.jpg
Labels: doc, non-breaking

#100 Refresh and Simplification of QSG README
  docs/quickstart/README.md
Labels: doc, non-breaking

#108 Typo fix in README.md
  README.md
Labels: doc, improvement
