Repository nv-morpheus/MRC, pull requests merged in 2022-12, with the labels that each got.

#217 Run CI on main branch
  .github/workflows/pull_request.yml
Labels: improvement, non-breaking, review: ready

#233 codecov updates
  .github/codecov.yml
  .github/workflows/ci_pipe.yml
  ci/scripts/github/build.sh
  ci/scripts/github/common.sh
  ci/scripts/github/test.sh
  ci/scripts/github/test_codecov.sh
  cmake/setup_coverage.cmake
Labels: bug, non-breaking, review: ready

#243 lazy instantiation of the nvml singleton
  cpp/mrc/src/internal/system/device_info.cpp
Labels: improvement, non-breaking

#248 Fix potential race condition
  cpp/mrc/src/internal/control_plane/server.cpp
  cpp/mrc/src/internal/control_plane/server.hpp
  cpp/mrc/src/internal/control_plane/server/connection_manager.cpp
  cpp/mrc/src/internal/control_plane/server/connection_manager.hpp
  cpp/mrc/src/internal/resources/manager.cpp
  cpp/mrc/src/tests/test_codable.cpp
Labels: bug, non-breaking

#239 C++20 version of upcoming C++23 std::expected
  cmake/dependencies.cmake
  cmake/deps/Configure_expected.cmake
  cpp/mrc/CMakeLists.txt
  cpp/mrc/include/mrc/core/std23_expected.hpp
  cpp/mrc/src/internal/control_plane/server.cpp
  cpp/mrc/src/internal/expected.hpp
  cpp/mrc/src/tests/CMakeLists.txt
  cpp/mrc/src/tests/test_expected.cpp
Labels: improvement, non-breaking, review: ready, blocker

#236 Development container image
  .devcontainer/devcontainer.json
  .devcontainer/scripts/post_start.sh
  Dockerfile
  ci/conda/README.md
  ci/runner/Dockerfile
  ci/runner/build_and_push.sh
Labels: non-breaking, feature request, review: ready

#246 Remove draconian regex filter that eliminates entire tests from being run
  .github/workflows/ci_pipe.yml
  ci/scripts/github/test.sh
  ci/scripts/github/test_codecov.sh
  cpp/mrc/CMakeLists.txt
  cpp/mrc/src/internal/control_plane/server.cpp
  cpp/mrc/src/tests/common.hpp
  cpp/mrc/src/tests/test_expected.cpp
  cpp/mrc/src/tests/test_ucx.cpp
  cpp/mrc/tests/test_mrc.hpp
Labels: improvement, non-breaking, review: ready

#244 C++20 Coroutines
  .clang-tidy
  cpp/mrc/CMakeLists.txt
  cpp/mrc/include/mrc/core/thread.hpp
  cpp/mrc/include/mrc/coroutines/concepts/awaitable.hpp
  cpp/mrc/include/mrc/coroutines/concepts/buffer.hpp
  cpp/mrc/include/mrc/coroutines/concepts/executor.hpp
  cpp/mrc/include/mrc/coroutines/concepts/promise.hpp
  cpp/mrc/include/mrc/coroutines/concepts/range_of.hpp
  cpp/mrc/include/mrc/coroutines/detail/void_value.hpp
  cpp/mrc/include/mrc/coroutines/event.hpp
  cpp/mrc/include/mrc/coroutines/generator.hpp
  cpp/mrc/include/mrc/coroutines/latch.hpp
  cpp/mrc/include/mrc/coroutines/ring_buffer.hpp
  cpp/mrc/include/mrc/coroutines/schedule_policy.hpp
  cpp/mrc/include/mrc/coroutines/sync_wait.hpp
  cpp/mrc/include/mrc/coroutines/task.hpp
  cpp/mrc/include/mrc/coroutines/thread_local_context.hpp
  cpp/mrc/include/mrc/coroutines/thread_pool.hpp
  cpp/mrc/include/mrc/coroutines/when_all.hpp
  cpp/mrc/src/public/core/thread.cpp
  cpp/mrc/src/public/coroutines/event.cpp
  cpp/mrc/src/public/coroutines/sync_wait.cpp
  cpp/mrc/src/public/coroutines/thread_local_context.cpp
  cpp/mrc/src/public/coroutines/thread_pool.cpp
  cpp/mrc/tests/CMakeLists.txt
  cpp/mrc/tests/coroutines/test_event.cpp
  cpp/mrc/tests/coroutines/test_latch.cpp
  cpp/mrc/tests/coroutines/test_ring_buffer.cpp
  cpp/mrc/tests/coroutines/test_task.cpp
  cpp/mrc/tests/test_thread.cpp
Labels: non-breaking, feature request, review: ready

#242 Update Versions for 23.01
  CMakeLists.txt
  ci/conda/environments/dev_env.yml
  ci/conda/environments/dev_env_nogcc.yml
  ci/conda/recipes/libmrc/conda_build_config.yaml
  ci/conda/recipes/libmrc/meta.yaml
  cmake/dependencies.cmake
  cmake/deps/Configure_libcudacxx.cmake
  cmake/deps/Configure_taskflow.cmake
  docs/quickstart/CMakeLists.txt
  docs/quickstart/environment_cpp.yml
  python/tests/test_module_registry.py
Labels: improvement, breaking

#258 Update Task destructor logic to conform to the standard
  cpp/mrc/include/mrc/coroutines/task.hpp
Labels: improvement, non-breaking, review: ready

#256 Missing <unordered_map> header; caught by gcc12
  cpp/mrc/include/mrc/core/utils.hpp
Labels: bug, non-breaking, review: ready
