Repository nv-morpheus/MRC, pull requests merged in 2023-03, with the labels that each got.

#294 Use AWS OIDC to get AWS creds
  .github/workflows/ci_pipe.yml
  .github/workflows/pull_request.yml
Labels: improvement, non-breaking

#295 Set AWS credentials lifetime to 12h
  .github/workflows/ci_pipe.yml
Labels: improvement, non-breaking

#296 Update workflow `permissions` block
  .github/workflows/ci_pipe.yml
  .github/workflows/pull_request.yml
Labels: improvement, non-breaking

#293 Pointer cast macro
  cpp/mrc/include/mrc/utils/macros.hpp
  cpp/mrc/tests/CMakeLists.txt
  cpp/mrc/tests/test_macros.cpp
Labels: improvement, non-breaking, 3 - Ready for Review

#292 Cleanup top-level forward.hpp and types.hpp
  cpp/mrc/include/mrc/forward.hpp
  cpp/mrc/include/mrc/types.hpp
Labels: bug, breaking, 3 - Ready for Review
