Repository nv-morpheus/MRC, pull requests merged in 2023-09, with the labels that each got.

#377 Fixing an issue with `update-versions.sh` which always blocked CI
  ci/release/update-version.sh
Labels: bug, non-breaking

#375 Updates for MRC/Morpheus to build in the same RAPIDS devcontainer environment
  CMakeLists.txt
  dependencies.yaml
  python/mrc/_pymrc/CMakeLists.txt
Labels: non-breaking, feature request

#376 Make Quick Start Guide not use `make_node_full`
  docs/quickstart/python/mrc_qs_python/ex02_reactive_operators/README.md
Labels: doc, non-breaking

#382 Revert boost upgrade, and update clang to v16
  ci/conda/environments/clang_env.yml
  ci/conda/environments/dev_env.yml
Labels: bug, non-breaking, 3 - Ready for Review

#383 Add missing flags to docker command to mount the working dir and set -cap-add=sys_nice
  README.md
Labels: doc, non-breaking, priority 2, 3 - Ready for Review

#396 update rapidsai/ci to rapidsai/ci-conda
  .github/workflows/pull_request.yml
  Dockerfile
Labels: improvement, non-breaking

#391 Safe handling of control plane promises & fix CI
  ci/conda/environments/clang_env.yml
  ci/conda/environments/dev_env.yml
  ci/scripts/cpp_checks.sh
  ci/scripts/github/checks.sh
  cpp/mrc/CMakeLists.txt
  cpp/mrc/include/mrc/core/userspace_threads.hpp
  cpp/mrc/include/mrc/core/utils.hpp
  cpp/mrc/include/mrc/types.hpp
  cpp/mrc/src/internal/control_plane/client.cpp
  cpp/mrc/src/internal/control_plane/client.hpp
  cpp/mrc/src/internal/control_plane/client/instance.cpp
  cpp/mrc/src/internal/control_plane/client/subscription_service.cpp
  cpp/mrc/src/internal/control_plane/server.cpp
  cpp/mrc/src/internal/control_plane/server.hpp
  cpp/mrc/src/internal/data_plane/client.cpp
  cpp/mrc/src/internal/data_plane/data_plane_resources.cpp
  cpp/mrc/src/internal/data_plane/server.cpp
  cpp/mrc/src/internal/executor/executor_definition.cpp
  cpp/mrc/src/internal/grpc/client_streaming.hpp
  cpp/mrc/src/internal/grpc/progress_engine.cpp
  cpp/mrc/src/internal/grpc/progress_engine.hpp
  cpp/mrc/src/internal/grpc/promise_handler.cpp
  cpp/mrc/src/internal/grpc/promise_handler.hpp
  cpp/mrc/src/internal/grpc/server.cpp
  cpp/mrc/src/internal/grpc/server.hpp
  cpp/mrc/src/internal/grpc/server_streaming.hpp
  cpp/mrc/src/internal/pipeline/manager.cpp
  cpp/mrc/src/internal/pipeline/pipeline_instance.cpp
  cpp/mrc/src/internal/pipeline/pipeline_instance.hpp
  cpp/mrc/src/internal/remote_descriptor/manager.cpp
  cpp/mrc/src/internal/resources/manager.cpp
  cpp/mrc/src/internal/resources/manager.hpp
  cpp/mrc/src/internal/segment/segment_instance.cpp
  cpp/mrc/src/internal/service.cpp
  cpp/mrc/src/internal/service.hpp
  cpp/mrc/src/internal/system/fiber_manager.cpp
  cpp/mrc/src/internal/system/fiber_task_queue.cpp
  cpp/mrc/src/internal/system/fiber_task_queue.hpp
  cpp/mrc/src/internal/system/thread.cpp
  cpp/mrc/src/tests/CMakeLists.txt
  cpp/mrc/src/tests/test_control_plane.cpp
  cpp/mrc/src/tests/test_pipeline.cpp
  cpp/mrc/src/tests/test_service.cpp
  cpp/mrc/tests/modules/test_segment_modules.cpp
  cpp/mrc/tests/modules/test_stream_buffer_modules.cpp
Labels: bug, non-breaking

#394 Add local CI scripts & rebase docker image
  .github/workflows/ci_pipe.yml
  .github/workflows/pull_request.yml
  .gitignore
  README.md
  ci/scripts/bootstrap_local_ci.sh
  ci/scripts/github/build.sh
  ci/scripts/github/common.sh
  ci/scripts/github/conda.sh
  ci/scripts/github/docs.sh
  ci/scripts/github/post_benchmark.sh
  ci/scripts/github/pre_benchmark.sh
  ci/scripts/github/test.sh
  ci/scripts/github/test_codecov.sh
  ci/scripts/run_ci_local.sh
Labels: improvement, non-breaking

#402 Fix EdgeHolder from incorrectly reporting an active connection
  cpp/mrc/include/mrc/edge/edge_holder.hpp
  cpp/mrc/tests/test_edges.cpp
Labels: bug, non-breaking
