Repository nv-morpheus/MRC, pull requests merged in 2024-03, with the labels that each got.

#451 Update cast_from_pyobject to throw on unsupported types rather than returning null
  python/mrc/_pymrc/include/pymrc/utils.hpp
  python/mrc/_pymrc/src/utils.cpp
  python/mrc/_pymrc/tests/test_utils.cpp
Labels: bug, breaking

#456 Removing the INFO log when creating an AsyncioRunnable
  python/mrc/_pymrc/include/pymrc/asyncio_runnable.hpp
Labels: bug, non-breaking

#453 Add `TestScheduler` to support testing time-based coroutines without waiting for timeouts
  cpp/mrc/CMakeLists.txt
  cpp/mrc/include/mrc/coroutines/test_scheduler.hpp
  cpp/mrc/src/public/coroutines/test_scheduler.cpp
Labels: non-breaking, feature request, conda-build
