Repository nv-morpheus/MRC, pull requests merged in 2024-10, with the labels that each got.

#505 Adding environment variable to allow skip NUMA node check
  cpp/mrc/src/internal/system/partitions.cpp
Labels: bug, non-breaking

#503 Fix Incorrect docstring in `mrc.core.coro`
  python/mrc/_pymrc/include/pymrc/coro.hpp
  python/mrc/core/coro.cpp
  python/mrc/core/executor.cpp
Labels: doc, non-breaking

#500 Fix get-pr-info gha reference
  .github/workflows/pr.yaml
Labels: bug, non-breaking

#506 devcontainer: replace VAULT_HOST with AWS_ROLE_ARN
  .devcontainer/conda/Dockerfile
  .devcontainer/conda/devcontainer.json
  .devcontainer/opt/mrc/conda/Dockerfile
  .devcontainer/opt/mrc/conda/devcontainer.json
Labels: improvement, non-breaking

#514 fix build interface includes
  cpp/mrc/CMakeLists.txt
Labels: bug, non-breaking
