Repository nv-morpheus/MRC, pull requests merged in 2024-04, with the labels that each got.

#455 Add JSONValues container for holding Python values as JSON objects if possible, and as pybind11::object otherwise
  ci/conda/recipes/libmrc/meta.yaml
  ci/iwyu/mappings.imp
  conda/environments/all_cuda-121_arch-x86_64.yaml
  conda/environments/ci_cuda-121_arch-x86_64.yaml
  dependencies.yaml
  python/mrc/_pymrc/CMakeLists.txt
  python/mrc/_pymrc/include/pymrc/types.hpp
  python/mrc/_pymrc/include/pymrc/utilities/json_values.hpp
  python/mrc/_pymrc/include/pymrc/utilities/object_cache.hpp
  python/mrc/_pymrc/include/pymrc/utils.hpp
  python/mrc/_pymrc/src/utilities/json_values.cpp
  python/mrc/_pymrc/src/utils.cpp
  python/mrc/_pymrc/tests/CMakeLists.txt
  python/mrc/_pymrc/tests/test_json_values.cpp
  python/mrc/_pymrc/tests/test_utils.cpp
Labels: non-breaking, feature request, conda-build

#460 Update CR year
  ci/check_style.sh
  ci/scripts/github/checks.sh
  docs/quickstart/CMakeLists.txt
  docs/quickstart/python/mrc_qs_python/_version.py
  docs/quickstart/python/mrc_qs_python/ex02_reactive_operators/run.py
Labels: bug, non-breaking

#458 Add pybind11 type caster for JSONValues
  python/mrc/_pymrc/include/pymrc/utilities/json_values.hpp
  python/mrc/_pymrc/tests/test_json_values.cpp
  python/mrc/tests/utils.cpp
  python/tests/test_json_values_cast.py
Labels: improvement, non-breaking

#467 Update minimum requirements
  README.md
Labels: doc, non-breaking

#464 Add maximum simultaneous tasks support to `TaskContainer`
  ci/conda/recipes/libmrc/meta.yaml
  ci/iwyu/mappings.imp
  conda/environments/all_cuda-121_arch-x86_64.yaml
  conda/environments/ci_cuda-121_arch-x86_64.yaml
  cpp/mrc/include/mrc/coroutines/task_container.hpp
  cpp/mrc/include/mrc/coroutines/test_scheduler.hpp
  cpp/mrc/src/public/coroutines/task_container.cpp
  cpp/mrc/src/public/coroutines/test_scheduler.cpp
  cpp/mrc/tests/coroutines/test_task_container.cpp
  dependencies.yaml
  python/mrc/_pymrc/CMakeLists.txt
  python/mrc/_pymrc/include/pymrc/asyncio_runnable.hpp
  python/mrc/_pymrc/include/pymrc/types.hpp
  python/mrc/_pymrc/include/pymrc/utilities/json_values.hpp
  python/mrc/_pymrc/include/pymrc/utilities/object_cache.hpp
  python/mrc/_pymrc/include/pymrc/utils.hpp
  python/mrc/_pymrc/src/utilities/json_values.cpp
  python/mrc/_pymrc/src/utils.cpp
  python/mrc/_pymrc/tests/CMakeLists.txt
  python/mrc/_pymrc/tests/test_json_values.cpp
  python/mrc/_pymrc/tests/test_utils.cpp
Labels: non-breaking, feature request

#469 Downgrade doxygen to match Morpheus
  conda/environments/all_cuda-121_arch-x86_64.yaml
  conda/environments/ci_cuda-121_arch-x86_64.yaml
  dependencies.yaml
Labels: improvement, non-breaking

#465 Consolidate redundant split_string_to_array, split_string_on & split_path methods
  ci/iwyu/mappings.imp
  cpp/mrc/CMakeLists.txt
  cpp/mrc/include/mrc/utils/string_utils.hpp
  cpp/mrc/src/internal/utils/parse_config.cpp
  cpp/mrc/src/internal/utils/parse_ints.cpp
  cpp/mrc/src/public/utils/string_utils.cpp
  cpp/mrc/tests/CMakeLists.txt
  cpp/mrc/tests/test_string_utils.cpp
  python/mrc/_pymrc/include/pymrc/utilities/json_values.hpp
  python/mrc/_pymrc/src/utilities/json_values.cpp
Labels: improvement, non-breaking

#473 Add auto register helpers to AsyncSink and AsyncSource
  ci/scripts/cpp_checks.sh
  python/mrc/_pymrc/include/pymrc/asyncio_runnable.hpp
Labels: bug, non-breaking, conda-build, ! - Hotfix

#475 [RELEASE] MRC v24.03.01
  CHANGELOG.md
  ci/scripts/cpp_checks.sh
  python/mrc/_pymrc/include/pymrc/asyncio_runnable.hpp
Labels: ! - Release
